# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - func-coppa-cop-analytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './app' # set this to the path to your web app project, now using the app subfolder
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
          pip install azure-cosmos==4.5.1 --force-reinstall
          pip list | grep azure

      - name: Test dependencies
        run: |
          source venv/bin/activate
          python test_dependencies.py
          python -c "import azure.cosmos; print('Azure Cosmos installed successfully')"

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          # Remove any existing zip file
          rm -f release.zip
          # Create zip excluding unnecessary files
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "*.md" ".DS_Store" "__pycache__/*" "*.pyc" "azure-deploy/*" "chatbot-analytics-azure-deploy/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B5FB86811EDE41EBAAE371FB190F089E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D168315B4AF949078CA089299755B361 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01B157E0C36F41B7ADFE4A30827286A0 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-coppa-cop-analytics'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          